name: shadcn_fields_example
description: Example app showcasing all 21 ShadCN Flutter form fields for ChampionForms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0-88.0.dev

dependencies:
  flutter:
    sdk: flutter
  championforms_shadcn_fields:
    path: ../
  championforms:
    git:
      url: https://github.com/cotw-fabier/championforms.git

  shadcn_flutter: ^0.0.47

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
